unit:
  name: datagrid
  description: Red Hat Data Grid

service:
  user: "{{ unit.name }}"
  group: "{{ unit.name }}"

install_dir: "/opt/{{ unit.name }}"

ports:
  - 11222/tcp  # cache endpoint
  - 7800/tcp   # site clustering
  - 7801/tcp   # cross site TCP
  - 46000/tcp  # internal FD_SOCK
  - 45000/tcp  # xsite FD_SOCK

xsite_ssl:
  dir: "{{ certs_dir | default('.') }}"
  name: "{{ datagrid_certs | default('xsite.jks') }}"
  alias: xsite
  key_password: "changeit"
  store_password: "changeit"
  type: JCEKS
  alg: Blowfish
  size: 56